[platformio]
default_envs = pico_w

[env:pico_w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library@^3.0.2
build_flags =
  -D SERIAL_BAUD=115200
  -D TCP_PORT=7777
  -D I2C_SDA_PIN=4
  -D I2C_SCL_PIN=5
  -D PCA9685_ADDRESS=0x40
  -D SERVO_EE_CHANNEL=0
  -D SERVO_Q1_CHANNEL=1
  -D SERVO_Q2_CHANNEL=2
  -D SERVO_Q3_CHANNEL=3
  -D BUZZER_PIN=15
